<a href="https://colab.research.google.com/github/Turqan522/MachineLearning/blob/main/student_exam_performance.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import linear_model
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import OneHotEncoder,OrdinalEncoder,StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer

In [ ]:
df=pd.read_csv('student_exam_performance (1).csv')
df

,student_id,age,gender,education_level,school_type,family_income,parent_education,urban_rural,previous_exam_score,previous_gpa,...,exam_difficulty,exam_preparation_days,questions_attempted,questions_correct,time_management_score,exam_anxiety_level,exam_score,performance_grade,pass_status,performance_level
0,STU_000001,20,Female,High School,Public,Middle,NaN,Rural,78.36,2.95,...,Medium,27,95,86,NaN,9.39,90.40,A,Pass,High
1,STU_000002,17,Male,High School,Public,Middle,NaN,Suburban,73.40,2.89,...,Easy,4,100,86,87.17,6.31,86.21,A,Pass,High
2,STU_000003,18,Other,Undergraduate,Public,Middle,Master,Urban,82.76,3.35,...,Easy,28,96,74,63.77,9.87,76.11,B,Pass,Medium
3,STU_000004,20,Male,High School,Public,Middle,High School,Suburban,60.61,2.57,...,Medium,16,97,77,59.51,9.68,79.74,B,Pass,Medium
4,STU_000005,16,Female,High School,Private,High,Bachelor,Suburban,74.79,2.84,...,Medium,28,98,52,84.64,10.00,50.66,D,Pass,Low
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,STU_099996,17,Male,Undergraduate,Public,Upper-Middle,NaN,Suburban,78.73,NaN,...,Medium,5,95,62,76.13,8.36,66.46,C,Pass,Medium
99996,STU_099997,14,Female,High School,Public,Upper-Middle,Bachelor,Suburban,75.70,2.98,...,Easy,24,94,91,84.29,8.68,96.54,A,Pass,High
99997,STU_099998,16,Female,High School,Public,Upper-Middle,High School,Suburban,84.69,3.27,...,Medium,24,85,65,62.32,9.97,74.66,C,Pass,Medium
99998,STU_099999,15,Female,High School,Private,High,Master,Rural,74.70,3.06,...,Medium,28,93,81,100.00,10.00,85.85,A,Pass,High
99999,STU_100000,18,Female,Undergraduate,Charter,Lower-Middle,NaN,Urban,76.73,2.97,...,Medium,1,92,52,NaN,10.00,54.40,D,Pass,Low

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 44 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   student_id                  100000 non-null  object
 1   age                         100000 non-null  int64
 2   gender                      100000 non-null  object
 3   education_level             100000 non-null  object
 4   school_type                 100000 non-null  object
 5   family_income               100000 non-null  object
 6   parent_education            93474 non-null   object
 7   urban_rural                 100000 non-null  object
 8   previous_exam_score         100000 non-null  float64
 9   previous_gpa                92207 non-null   float64
 10  attendance_percentage       90137 non-null   float64
 11  assignment_completion_rate  100000 non-null  float64
 12  class_participation         100000 non-null  object
 13  study_hours_per_day         100000 non-null  float64
 14  self_study_hours            100000 non-null  float64
 15  private_tuition             100000 non-null  int64
 16  online_learning_hours       100000 non-null  float64
 17  study_consistency           100000 non-null  object
 18  study_environment           100000 non-null  object
 19  study_method                100000 non-null  object
 20  revision_frequency          100000 non-null  object
 21  practice_tests_completed    100000 non-null  int64
 22  notes_quality               91593 non-null   object
 23  sleep_hours                 100000 non-null  float64
 24  sleep_quality               93006 non-null   object
 25  daily_screen_time           100000 non-null  float64
 26  physical_activity_hours     100000 non-null  float64
 27  break_frequency             100000 non-null  object
 28  stress_level                100000 non-null  int64
 29  motivation_level            100000 non-null  object
 30  internet_access             100000 non-null  int64
 31  device_availability         97035 non-null   object
 32  educational_app_usage       100000 non-null  object
 33  online_course_hours         100000 non-null  float64
 34  exam_difficulty             100000 non-null  object
 35  exam_preparation_days       100000 non-null  int64
 36  questions_attempted         100000 non-null  int64
 37  questions_correct           100000 non-null  int64
 38  time_management_score       90387 non-null   float64
 39  exam_anxiety_level          100000 non-null  float64
 40  exam_score                  100000 non-null  float64
 41  performance_grade           100000 non-null  object
 42  pass_status                 100000 non-null  object
 43  performance_level           100000 non-null  object
dtypes: float64(14), int64(8), object(22)
memory usage: 33.6+ MB

In [ ]:
df.describe()

,age,previous_exam_score,previous_gpa,attendance_percentage,assignment_completion_rate,study_hours_per_day,self_study_hours,private_tuition,online_learning_hours,practice_tests_completed,...,physical_activity_hours,stress_level,internet_access,online_course_hours,exam_preparation_days,questions_attempted,questions_correct,time_management_score,exam_anxiety_level,exam_score
count,100000.000000,100000.000000,92207.000000,90137.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,...,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,90387.000000,100000.000000,100000.000000
mean,17.005740,69.531033,2.780892,84.616882,69.724405,2.995725,2.094970,0.299800,2.004763,5.509170,...,2.487579,9.375640,0.918760,2.999453,15.501440,92.492150,57.298240,78.398551,8.927373,61.950072
std,1.999562,11.379108,0.478218,7.922485,12.127179,1.719466,1.266066,0.458173,2.005719,2.501131,...,2.413386,1.081613,0.273205,2.983732,8.644356,4.609376,15.028787,14.105155,1.354875,15.863644
min,14.000000,30.000000,1.000000,46.340000,20.000000,0.500000,0.250000,0.000000,0.000000,0.000000,...,0.000000,5.000000,0.000000,0.000000,1.000000,85.000000,0.000000,17.030000,1.000000,0.000000
25%,15.000000,61.820000,2.460000,79.210000,61.480000,1.720000,1.170000,0.000000,0.580000,4.000000,...,0.720000,9.000000,1.000000,0.860000,8.000000,88.000000,47.000000,68.790000,8.220000,51.240000
50%,17.000000,69.530000,2.780000,84.750000,69.570000,2.670000,1.840000,0.000000,1.380000,5.000000,...,1.730000,10.000000,1.000000,2.080000,16.000000,92.000000,57.000000,79.000000,9.490000,61.960000
75%,19.000000,77.232500,3.110000,90.170000,77.920000,3.910000,2.730000,1.000000,2.770000,7.000000,...,3.480000,10.000000,1.000000,4.150000,23.000000,96.000000,67.000000,89.210000,10.000000,72.730000
max,20.000000,100.000000,4.000000,100.000000,100.000000,12.000000,10.000000,1.000000,15.000000,20.000000,...,12.000000,10.000000,1.000000,20.000000,30.000000,100.000000,100.000000,100.000000,10.000000,100.000000

In [ ]:
df.isna().sum()

student_id                       0
age                              0
gender                           0
education_level                  0
school_type                      0
family_income                    0
parent_education              6526
urban_rural                      0
previous_exam_score              0
previous_gpa                  7793
attendance_percentage         9863
assignment_completion_rate       0
class_participation              0
study_hours_per_day              0
self_study_hours                 0
private_tuition                  0
online_learning_hours            0
study_consistency                0
study_environment                0
study_method                     0
revision_frequency               0
practice_tests_completed         0
notes_quality                 8407
sleep_hours                      0
sleep_quality                 6994
daily_screen_time                0
physical_activity_hours          0
break_frequency                  0
stress_level                     0
motivation_level                 0
internet_access                  0
device_availability           2965
educational_app_usage            0
online_course_hours              0
exam_difficulty                  0
exam_preparation_days            0
questions_attempted              0
questions_correct                0
time_management_score         9613
exam_anxiety_level               0
exam_score                       0
performance_grade                0
pass_status                      0
performance_level                0
dtype: int64

In [ ]:
df.nunique(
)

student_id                    100000
age                                7
gender                             3
education_level                    2
school_type                        3
family_income                      5
parent_education                   5
urban_rural                        3
previous_exam_score             6153
previous_gpa                     296
attendance_percentage           3911
assignment_completion_rate      6384
class_participation                3
study_hours_per_day             1073
self_study_hours                 856
private_tuition                    2
online_learning_hours           1330
study_consistency                  3
study_environment                  3
study_method                       5
revision_frequency                 3
practice_tests_completed          21
notes_quality                      3
sleep_hours                      793
sleep_quality                      4
daily_screen_time               1009
physical_activity_hours         1197
break_frequency                    3
stress_level                       6
motivation_level                   3
internet_access                    2
device_availability                2
educational_app_usage              3
online_course_hours             1804
exam_difficulty                    3
exam_preparation_days             30
questions_attempted               16
questions_correct                101
time_management_score           6204
exam_anxiety_level               759
exam_score                      8086
performance_grade                  5
pass_status                        2
performance_level                  3
dtype: int64

In [ ]:
x = df.drop(['student_id', 'exam_score'], axis=1)
y = df['exam_score']

In [ ]:
from sklearn.impute import SimpleImputer
num_pipeline=Pipeline([
    ('imputer',SimpleImputer(strategy='median')),
    ('scaler',StandardScaler())
])

In [ ]:
cat_pipeline=Pipeline([
    ('imputer',SimpleImputer(strategy='most_frequent')),
    ('encoder',OneHotEncoder())
])

In [ ]:
num_cols=x.select_dtypes(include=np.number).columns
cat_cols=x.select_dtypes(exclude=np.number).columns

In [ ]:
processor=ColumnTransformer([
    ('num',num_pipeline,num_cols),
    ('cat',cat_pipeline,cat_cols)
])

In [ ]:
model_pipeline=Pipeline([
    ('processor',processor),
    ('model',LinearRegression())
])

In [ ]:
X_train,X_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [ ]:
model_pipeline.fit(X_train,y_train)

Pipeline(steps=[('processor',
                 ColumnTransformer(transformers=[('num',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='median')),
                                                                  ('scaler',
                                                                   StandardScaler())]),
                                                  Index(['age', 'previous_exam_score', 'previous_gpa', 'attendance_percentage',
       'assignment_completion_rate', 'study_hours_per_day', 'self_study_hours',
       'private_tuition', 'online_learning_hours', 'prac...
       'parent_education', 'urban_rural', 'class_participation',
       'study_consistency', 'study_environment', 'study_method',
       'revision_frequency', 'notes_quality', 'sleep_quality',
       'break_frequency', 'motivation_level', 'device_availability',
       'educational_app_usage', 'exam_difficulty', 'performance_grade',
       'pass_status', 'performance_level'],
      dtype='object'))])),
                ('model', LinearRegression())])

In [ ]:
r2_value=model_pipeline.score(X_test,y_test)
r2_value

0.9887775299772823